# Generated by Django 4.2.1 on 2023-07-18 15:25

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='members',
            field=models.IntegerField(verbose_name='Members'),
        ),
    ]
