# Generated by Django 4.2.1 on 2023-07-18 15:26

from django.db import migrations
def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(name="Joe Silver", email="joe@email.com",members=3,phone="00000000", comment="This is a sample comment." ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_members'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
